Workflow - Install protoc
dapr/rust-sdk pull request #89
Opened 2023-02-03 22:56 UTC by robertojrojas

Signed-off-by: Roberto J Rojas <robertojrojas@gmail.com>

2023-02-03 23:35 UTC, artursouza commented on .github/workflows/ci.yml
> +      uses: arduino/setup-protoc@v1
Can you pin a protoc version to be installed?

2023-02-04 00:12 UTC, artursouza approved these changes

2023-02-04 00:41 UTC, artursouza requested changes
It is failing to install. Please, check it on your fork first.

2023-02-04 19:54 UTC, robertojrojas commented
@artursouza I've made some changes to the workflow and tested it locally. This should work now. 🤞

2023-02-07 17:24 UTC, merged